name: test
on:
- push
- pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - jruby
        - truffleruby
        - truffleruby+graalvm
        - '2.3'
        - '2'
        - '3.0'
        - '3'
        - '4'
        - ruby # latest release
        - head
        runs-on:
        - ubuntu-latest
        - windows-latest
        - macos-15-intel
        - macos-latest # arm64
        gemfile:
        - Gemfile_rack_1_faraday_1.rb
        - Gemfile_rack_2_faraday_1.rb
        - Gemfile_rack_3_faraday_2.rb

        exclude:
        - ruby-version: '2.3'
          gemfile: Gemfile_rack_3_faraday_2.rb
        - ruby-version: '2.3'
          runs-on: macos-latest
        - ruby-version: truffleruby
          runs-on: windows-latest
        - ruby-version: truffleruby+graalvm
          runs-on: windows-latest

    runs-on: ${{ matrix.runs-on }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:

    - uses: actions/checkout@v6

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake test
